---
baseurl: https://jonas.bike
languageCode: en-us
theme: hugo-theme-stack
paginate: 10
title: Jonas's blog
languages:
  en:
    languageName: English
    title: Jonas's blog
    weight: 1
disqusShortname: hugo-theme-stack
googleAnalytics: null
DefaultContentLanguage: en
hasCJKLanguage: false
permalinks:
  post: /:slug/
  page: /:slug/
params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: null
  footer:
    since: 2019
    customText: null
  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST
  sidebar:
    emoji: 🚴
    subtitle: >-
      Documenting my adventures and other things. Want to contact me? Send an email to contact@jonas.bike - I'll look at messages occasionally :-)
      Other projects: [CheckMySignal - Mobile coverage maps of South America](https://checkmysignal.net/).
    avatar:
      enabled: true
      local: true
      src: header.png
  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0
  comments:
    enabled: true
    provider: cusdis
    disqusjs:
      shortname: null
      apiUrl: null
      apiKey: null
      admin: null
      adminLabel: null
    utterances:
      repo: null
      issueTerm: pathname
      label: null
    remark42:
      host: null
      site: null
      locale: null
    vssue:
      platform: null
      owner: null
      repo: null
      clientId: null
      clientSecret: null
      autoCreateIssue: false
    waline:
      serverURL: null
      lang: null
      visitor: null
      avatar: null
      emoji:
        - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
      requiredMeta:
        - name
        - email
        - url
      placeholder: null
      locale:
        admin: Admin
    twikoo:
      envId: null
      region: null
      path: null
      lang: null
    cactus:
      defaultHomeserverUrl: https://matrix.cactus.chat:8448
      serverName: cactus.chat
      siteName: ""
    giscus:
      repo: null
      repoID: null
      category: null
      categoryID: null
      mapping: null
      lightTheme: null
      darkTheme: null
      reactionsEnabled: 1
      emitMetadata: 0
    gitalk:
      owner: null
      admin: null
      repo: null
      clientID: null
      clientSecret: null
    cusdis:
      host: https://cusdis.com
      id: f98c936a-8a3a-426d-8382-54cb95da4061
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc
  opengraph:
    twitter:
      site: null
      card: summary_large_image
  defaultImage:
    opengraph:
      enabled: false
      local: false
      src: null
  colorScheme:
    toggle: true
    default: auto
  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
menu:
  main: []
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/JonasCz
      params:
        icon: brand-github
    - identifier: stackoverflow
      name: Stack Overflow
      url: https://stackoverflow.com/users/4428462/jonascz
      params:
        icon: brand-stackoverflow
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200
markup:
  goldmark:
    renderer:
      unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
